services:
  web_site:
    build:
      context: ./apps/web_site
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web_site:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - ./apps/web_site/.env

  web_app:
    build:
      context: ./apps/web_app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./apps/web_app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - ./apps/web_app/.env

  web_admin:
    build:
      context: ./apps/web_admin
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./apps/web_admin:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - ./apps/web_admin/.env

  gateway_service:
    build:
      context: ./services/gateway_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./services/gateway_service:/app
    environment:
      - PYTHONPATH=/app

  user_service:
    build:
      context: ./services/user_service
    ports:
      - "8001:8001"
    volumes:
      - ./services/user_service:/app
    environment:
      - PYTHONPATH=/app

  ai_service:
    build:
      context: ./services/ai_service
    ports:
      - "8002:8002"
    volumes:
      - ./services/ai_service:/app
    environment:
      - PYTHONPATH=/app

  notification_service:
    build:
      context: ./services/notification_service
    ports:
      - "8003:8003"
    volumes:
      - ./services/notification_service:/app
    environment:
      - PYTHONPATH=/app
