services:
  postgres_db:
    image: postgres:16-alpine
    container_name: my_scaffold_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: scaffold_user
      POSTGRES_PASSWORD: scaffold_password
      POSTGRES_DB: scaffold_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_scaffold_network

  # Shared UI Components Storybook
  web_ui:
    build:
      context: .
      dockerfile: ./packages/web-ui/Dockerfile
    container_name: my_scaffold_web_ui
    ports:
      - "6006:6006" # Storybook default port
    volumes:
      - ./packages/web-ui:/app/packages/web-ui
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml:ro
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
      - ./package.json:/app/package.json:ro
      - /app/node_modules
      - /app/packages/web-ui/node_modules
    working_dir: /app/packages/web-ui
    networks:
      - my_scaffold_network
    command: sh -c "pnpm dev:build & pnpm dev"

  web_site:
    build:
      context: .
      dockerfile: ./apps/web_site/Dockerfile
    container_name: my_scaffold_web_site
    ports:
      - "3000:3000" # Host:Container (Using port 3000 for Next.js)
    volumes:
      - ./apps/web_site:/app/apps/web_site
      - ./packages:/app/packages:ro # Mount shared packages
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml:ro
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
      - ./package.json:/app/package.json:ro
      - /app/node_modules # Isolate node_modules in container
      - /app/apps/web_site/node_modules
    working_dir: /app/apps/web_site
    networks:
      - my_scaffold_network
    depends_on:
      - web_ui
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Enable hot reloading in Docker
    command: ["pnpm", "dev", "--hostname", "0.0.0.0", "--port", "3000"]
    # env_file:
    #   - ./apps/web_site/.env

  web_app:
    build:
      context: .
      dockerfile: ./apps/web_app/Dockerfile
    container_name: my_scaffold_web_app
    ports:
      - "3001:3001" # Host:Container
    volumes:
      - ./apps/web_app:/app/apps/web_app
      - ./packages:/app/packages:ro # Mount shared packages
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml:ro
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
      - ./package.json:/app/package.json:ro
      - /app/node_modules
      - /app/apps/web_app/node_modules
    working_dir: /app/apps/web_app
    networks:
      - my_scaffold_network
    depends_on:
      - web_ui
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Enable hot reloading in Docker
    command: ["pnpm", "dev", "--hostname", "0.0.0.0", "--port", "3001"]
    # env_file:
    #   - ./apps/web_app/.env

  web_admin:
    build:
      context: .
      dockerfile: ./apps/web_admin/Dockerfile
    container_name: my_scaffold_web_admin
    ports:
      - "3002:3002" # Host:Container
    volumes:
      - ./apps/web_admin:/app/apps/web_admin
      - ./packages:/app/packages:ro # Mount shared packages
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml:ro
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
      - ./package.json:/app/package.json:ro
      - /app/node_modules
      - /app/apps/web_admin/node_modules
    working_dir: /app/apps/web_admin
    networks:
      - my_scaffold_network
    depends_on:
      - web_ui
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Enable hot reloading in Docker
    command: ["pnpm", "dev", "--hostname", "0.0.0.0", "--port", "3002"]
    # env_file:
    #   - ./apps/web_admin/.env

  gateway_service:
    build:
      context: .
      dockerfile: ./services/gateway_service/Dockerfile
    container_name: my_scaffold_gateway_service
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db # Or other services it directly needs at startup
      - user_service
    volumes:
      - ./services/gateway_service:/app/services/gateway_service
      - ./packages:/app/packages:ro # Mount shared packages for API contracts
    networks:
      - my_scaffold_network
    environment:
      - USER_SERVICE_URL=my_scaffold_user_service:50051
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1 # For real-time logs
    command: ["uvicorn", "services.gateway_service.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  user_service:
    build:
      context: .
      dockerfile: ./services/user_service/Dockerfile
    container_name: my_scaffold_user_service
    ports:
      - "50051:50051" # Expose gRPC port
    depends_on:
      - postgres_db
    volumes:
      - ./services/user_service:/app/services/user_service
      - ./packages:/app/packages:ro # Mount shared packages for API contracts
    networks:
      - my_scaffold_network
    environment:
      - DATABASE_URL=postgresql://scaffold_user:scaffold_password@postgres_db:5432/scaffold_db
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1 # For real-time logs
    command: ["python", "-m", "services.user_service.app.main"]

  notification_service:
    build:
      context: .
      dockerfile: ./services/notification_service/Dockerfile
    container_name: my_scaffold_notification_service
    ports:
      - "8002:8000"
    depends_on:
      - postgres_db # If it needs db, or remove
    volumes:
      - ./services/notification_service:/app/services/notification_service
      - ./packages:/app/packages:ro # Mount shared packages for API contracts
    networks:
      - my_scaffold_network
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1 # For real-time logs
    command: ["uvicorn", "services.notification_service.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  ai_service:
    build:
      context: .
      dockerfile: ./services/ai_service/Dockerfile
    container_name: my_scaffold_ai_service
    ports:
      - "8003:8000"
    volumes:
      - ./services/ai_service:/app/services/ai_service
      - ./packages:/app/packages:ro # Mount shared packages for API contracts
    networks:
      - my_scaffold_network
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1 # For real-time logs
    command: ["uvicorn", "services.ai_service.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:

networks:
  my_scaffold_network:
    driver: bridge
